feat(map): Codegen for Protobuf Target
accordproject/concerto-codegen pull request #65
Opened 2023-10-17 15:45 UTC by Jonathan-Casey

2023-10-19 08:40 UTC, mttrbrts commented
Please confirm that the output compiles using the Protobuf tooling

2023-10-19 09:07 UTC, dselman approved these changes

2023-10-19 09:07 UTC, dselman requested changes
See note about namespaces / imports.

2023-11-09 13:43 UTC, dselman approved these changes
LGTM!

2023-11-09 17:15 UTC, merged