Removed backticks from mermaid code
accordproject/concerto-codegen pull request #94
Opened 2024-02-24 16:53 UTC by subhajit20

# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes
Removed backticks from mermaid code
Fix - https://github.com/accordproject/concerto/issues/665
### Flags

- <ONE>
- <TWO>

### Screenshots or Video

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `main` from `fork:branchname`

2024-02-24 16:54 UTC, subhajit20 commented
Hey @sanketshevkar, is this solution meaningful or are there any changes needed?

2024-02-26 11:14 UTC, ekarademir commented
@subhajit20 Could you sign your PRs please? https://github.com/dcoapp/app#how-it-works

2024-02-26 14:19 UTC, subhajit20 commented
Signed-off-by: Subhajit Ghosh subhajitstd07@gmail.comn

2024-02-26 14:22 UTC, subhajit20 commented
> @subhajit20 Could you sign your PRs please? https://github.com/dcoapp/app#how-it-works

Hey Done that.

2024-02-27 05:25 UTC, subhajit20 commented on lib/codegen/fromcto/mermaid/mermaidvisitor.js
>      visitClassDeclaration(classDeclaration, parameters, type = 'concept') {
Cool, I will do that
Thanks!!

2024-02-27 05:51 UTC, subhajit20 commented on lib/codegen/fromcto/mermaid/mermaidvisitor.js
>      visitClassDeclaration(classDeclaration, parameters, type = 'concept') {
Hey @sanketshevkar I have made certain changes and updated the snapshots.
Can you check that once and let me know if further changes are needed?

2024-02-27 06:01 UTC, sanketshevkar commented on lib/codegen/fromcto/mermaid/mermaidvisitor.js
>      visitClassDeclaration(classDeclaration, parameters, type = 'concept') {
@subhajit20 I don't think so this solves the issue, earlier you had removed back-ticks for classDeclaration name for declarations which has properties.
Now you have you removed back-ticks for classDeclaration name for declarations without properties.

Please test your changes on the editor I have shared.

2024-03-01 16:26 UTC, subhajit20 commented on lib/codegen/fromcto/mermaid/mermaidvisitor.js
>      visitClassDeclaration(classDeclaration, parameters, type = 'concept') {
Hey @sanketshevkar can you please check once I have made certain changes.

2024-03-04 07:51 UTC, sanketshevkar requested changes

2024-03-05 05:56 UTC, subhajit20 commented
hey @sanketshevkar I think this commit can removes backticks from properties

2024-03-06 11:21 UTC, sanketshevkar commented
Can you please share some sample model and its output mermaid diagram on this [editor ](https://mermaid.live/edit#pako:eNqFkE1rwzAMhv-K0XWmNG1pOlPKoLsOBr0NHyxstTPEcnAcWBby3-dkuY6hg74fXmkEGx2BAttg1716fCQMmpdMmEApoHcv1WZb7J1SF9mIUfP5LGxkS22-XDQLIZ6EueXk-WGE8c5onjT_gbnG0CIP_3MYA80kkLASis5xHtOQPymQBlVCR3fsm6zhdxT7HG8DW1A59SShbx1mWi8DdcemK9WiANQIX6C2EgZQ1X5zOB6r59Oh3p3qaldPEr5jLAuVBHI-x_S2Pmp2C-Bj6S_A6Qcb5WwN)

Also @mttrbrts should we add a test case to validate this?

2024-03-06 11:22 UTC, sanketshevkar commented
PR LGTM!

@mttrbrts @dselman can you please review the PR once?

2024-03-06 11:44 UTC, mttrbrts commented
Thanks for your contribution, @subhajit20 . The output is now looking much better! 🤩 

When I render one of the test cases in a mermaid editor I see that the properties are rendered without backticks, but that enum declarations values still have them. Can you make a similar change for that node too, please?

![image](https://github.com/accordproject/concerto-codegen/assets/7544022/3b0fbc24-496e-41e5-84eb-44d583768e8f)

@sanketshevkar

2024-03-06 16:23 UTC, subhajit20 commented
hey @mttrbrts done that.
Thanks!!f

2024-03-07 05:34 UTC, sanketshevkar commented
Good job @subhajit20 !! :)
LGTM!

2024-03-07 05:38 UTC, sanketshevkar commented
Let's wait for @mttrbrts's approval.

2024-03-07 09:17 UTC, dselman commented
Nice work @subhajit20. When are back ticks required? I.e. what characters does Mermaid require to be escaped with back ticks?

Can you please test this with our "kitchen sink" model and check the rendered output?
https://github.com/accordproject/concerto-codegen/blob/main/test/codegen/fromcto/data/model/hr.cto

2024-03-15 14:24 UTC, subhajit20 commented
hey @sanketshevkar @dselman is there anything further I have to do in this pr?

2024-03-15 15:38 UTC, subhajit20 commented
I just run the mentioned by @dselman  test using `npx mocha` and log the output  and all the properties of classes and enums are rendered without backticks here are two screenshots
- enum
![Screenshot 2024-03-15 at 9 05 09 PM](https://github.com/accordproject/concerto-codegen/assets/99127578/b193c90a-3c91-4f14-9ba9-9222e1806506)

- class
![Screenshot 2024-03-15 at 9 04 12 PM](https://github.com/accordproject/concerto-codegen/assets/99127578/132e3ecd-49db-4122-be07-0975164711a0)

2024-03-15 15:42 UTC, subhajit20 commented
And here is the mermaid editor output
![Screenshot 2024-03-15 at 9 11 52 PM](https://github.com/accordproject/concerto-codegen/assets/99127578/42fe4a85-4136-408c-94dc-0a077962bcc8)

2024-03-22 07:01 UTC, sanketshevkar approved these changes

2024-03-22 09:22 UTC, mttrbrts approved these changes

2024-03-22 09:22 UTC, merged